vich_uploader:
    db_driver: orm

    mappings:
        piece_jointe_commande:
            uri_prefix: /uploads/pieces
            upload_destination: '%kernel.project_dir%/public/uploads/pieces'
            namer: Vich\UploaderBundle\Naming\SmartUniqueNamer

        commandes_fichiers:
            uri_prefix: /uploads/fichiers/commandes
            upload_destination: '%kernel.project_dir%/public/uploads/fichiers/commandes'
            namer: Vich\UploaderBundle\Naming\SmartUniqueNamer
            delete_on_update: true
            delete_on_remove: true

        commandes_fichiers2:
            uri_prefix: /uploads/fichiers/commandes
            upload_destination: '%kernel.project_dir%/public/uploads/fichiers/commandes2'
            namer: Vich\UploaderBundle\Naming\SmartUniqueNamer
            delete_on_update: true
            delete_on_remove: true

        commandes_fichiers3:
            uri_prefix: /uploads/fichiers/commandes
            upload_destination: '%kernel.project_dir%/public/uploads/fichiers/commandes3'
            namer: Vich\UploaderBundle\Naming\SmartUniqueNamer
            delete_on_update: true
            delete_on_remove: true
